[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2"
rand = "0.8.5"
image = "0.24.7"
rayon = "1.8"

[workspace]
members = ["raytracer_headless", "raytracer_runtime", "raytracer_gpu"]