[package]
name = "raytracer_headless"
version = "0.1.0"
edition = "2021"

[dependencies]
raytracer = { path = "../" }
num-traits = "0.2"
rand = "0.8.5"
image = "0.24.7"
rayon = "1.8"
indicatif = { version = "0.17.7", features = ["rayon"] }