mod math;
pub use math::{AABB, Ray, Scalar, Vec3, radians, random};
mod scene;
pub use scene::{Bounded, Hittable, Object, RayHit, Renderable, Scene};
mod bvh;
pub use bvh::BVH;
mod camera;
pub use camera::Camera;
mod materials;
pub use materials::{Material, Scattered};
mod shapes;
pub use shapes::{Cube, Sphere};
mod renderer;
pub use renderer::render;
