mod math;
pub use math::{radians, random, Ray, Vec3, AABB, Scalar};
mod scene;
pub use scene::{Scene, Object, RayHit, Hittable, Renderable, Bounded};
mod bvh;
pub use bvh::BVH;
mod camera;
pub use camera::Camera;
mod materials;
pub use materials::{Material, Scattered};
mod shapes;
pub use shapes::{Sphere, Cube};
mod renderer;
pub use renderer::render;